CREATE TABLE customer (
    customer_id INTEGER PRIMARY KEY,
    age INTEGER,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(100),
    purchase_amount_usd INTEGER,
    location VARCHAR(100),
    size VARCHAR(20),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    promo_code_used VARCHAR(10),
    previous_purchases INTEGER,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50)
);

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
SELECT COUNT(*) FROM customer;


--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender
ORDER BY revenue;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,AVG(review_rating) FROM customer
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping

SELECT AVG(purchase_amount_usd),shipping_type FROM customer
WHERE shipping_type = 'Express' OR shipping_type = 'Standard'
GROUP BY shipping_type
ORDER BY AVG(purchase_amount_usd);

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 

SELECT subscription_status,SUM(purchase_amount_usd) FROM customer
GROUP BY subscription_status
ORDER BY SUM(purchase_amount_usd);

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;



SELECT * FROM customer LIMIT 4;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT
    CASE
        WHEN previous_purchases = 1  THEN 'New'
        WHEN previous_purchases <= 10 THEN 'Returning'
        WHEN previous_purchases >= 11 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_segment_number
FROM customer
GROUP BY
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases <= 10 THEN 'Returning'
        WHEN previous_purchases >= 11 THEN 'Loyal'
    END
ORDER BY customer_segment_number;



--Q8. What are the top 3 most purchased products within each category? 

SELECT item_purchased,category,COUNT(item_purchased) FROM customer
GROUP BY category,item_purchased
ORDER BY COUNT(item_purchased) DESC;

SELECT *
FROM (SELECT item_purchased,category,COUNT(item_purchased),
DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rank_category
FROM customer
GROUP BY category,item_purchased)
WHERE rank_category <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT customer_id,subscription_status,previous_purchases FROM customer
WHERE subscription_status = 'Yes' AND previous_purchases > 5 
ORDER BY previous_purchases DESC;

--Q10. What is the revenue contribution of each age group?

SELECT
    age,
    CASE
        WHEN age < 18 THEN 'Child'
        WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN age BETWEEN 31 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group
FROM customer;


SELECT
CASE
        WHEN age < 18 THEN 'Child'
        WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN age BETWEEN 31 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,COUNT(purchase_amount_usd)
FROM customer
GROUP BY CASE
        WHEN age < 18 THEN 'Child'
        WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN age BETWEEN 31 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END
ORDER BY COUNT(purchase_amount_usd) DESC;






